url: http://localhost:3000
tunnel: 06551683-130e-41d8-9bec-71d7c799bbac
credentials-file: C:\Users\maftu\.cloudflared\06551683-130e-41d8-9bec-71d7c799bbac.json

ingress:
  - hostname: icbs.my.id
    service: http://localhost:3000
  - service: http_status:404 